{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{include file="field_select.tpl" field=$schema}}

<div class="settings-submit-wrapper">
	<input type="submit" value="{{$submit}}" class=" btn btn-default settings-submit" name="redstrap3-settings-submit" />
</div>
